/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable */

#ifndef _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable
#define _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable
 * Method:    replaceComponent
 * Signature: (Ljava/lang/String;Ljava/lang/String;[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable_replaceComponent
  (JNIEnv *, jobject, jstring, jstring, jintArray, jstring);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFamilyTable_setDebug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
