/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplifiedlogic_nitro_jlink_cpp_JCFeature */

#ifndef _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFeature
#define _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFeature
 * Method:    featuresSuppress
 * Signature: (Ljava/lang/String;Ljava/lang/String;[IZ)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFeature_featuresSuppress
  (JNIEnv *, jobject, jstring, jstring, jintArray, jboolean);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFeature
 * Method:    featuresResume
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFeature_featuresResume
  (JNIEnv *, jobject, jstring, jstring, jintArray);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFeature
 * Method:    featuresDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;[IZ)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFeature_featuresDelete
  (JNIEnv *, jobject, jstring, jstring, jintArray, jboolean);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFeature
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFeature_setDebug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
