/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplifiedlogic_nitro_jlink_cpp_JCFile */

#ifndef _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFile
#define _Included_com_simplifiedlogic_nitro_jlink_cpp_JCFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFile
 * Method:    featureSuppress
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFile_featureSuppress
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCFile
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCFile_setDebug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
