/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplifiedlogic_nitro_jlink_cpp_JCConnection */

#ifndef _Included_com_simplifiedlogic_nitro_jlink_cpp_JCConnection
#define _Included_com_simplifiedlogic_nitro_jlink_cpp_JCConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCConnection
 * Method:    connect
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCConnection_connect
  (JNIEnv *, jclass);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCConnection
 * Method:    connectById
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCConnection_connectById
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCConnection
 * Method:    setConnectionDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCConnection_setConnectionDebug
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_simplifiedlogic_nitro_jlink_cpp_JCConnection
 * Method:    setSessionDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_simplifiedlogic_nitro_jlink_cpp_JCConnection_setSessionDebug
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
